services:
  api:
    container_name: task-manager-api
    ports:
      - "8081:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=db;Port=5432;Database=taskdb;Username=postgres;Password=postgres
      Jwt__Key: b3BlbmFpLWp3dC1zZWNyZXQta2V5LTI1Ni1iaXRzISE=
      Jwt__Issuer: TaskManagerApi
      Jwt__Audience: TaskManagerApiClient
      Jwt__ExpiresMinutes: 2

  db:
    container_name: task-manager-db
    ports:
      - "9090:5432"
    environment:
      POSTGRES_DB: taskdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
